// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lcnzovtftmaatcgcayhb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxjbnpvdnRmdG1hYXRjZ2NheWhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUyNjk1MzksImV4cCI6MjA1MDg0NTUzOX0.bdvoltAamXPP05APkN7CxNIsQNO-LQRrB-kADbRWnIo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);